---
- name: Backup Database
  hosts: pp-DBslave
  become: true
  gather_facts: true
  # vars:
  #   db_name: wordpress
  #   db_user_name: wordpress
  #   db_user_password: wordpress

  tasks:
    - name: Create variables
      set_fact:
        db_file_name: "/tmp/fullbackup_{{ ansible_date_time.epoch }}.sql"

    - name: Confirm hostname
      ansible.builtin.debug:
        msg: Logged into the server.

    - name: Download Database to server
      ansible.builtin.shell: |
        mysqldump -u root -p123 \
          --all-databases \
          --add-drop-table \
          --add-locks \
          --create-options \
          --disable-keys \
          --extended-insert \
          --single-transaction \
          --quick \
          --set-charset \
          --events \
          --routines \
          --triggers \
          > "{{ db_file_name }}"

    - name: Wait until the database backup completed on server
      wait_for:
        path: "{{ db_file_name }}"
        state: present
        msg: "Timeout to find file {{ db_file_name }}"

    - name: Copy backups to pp-front
      ansible.builtin.shell: |
        rsync -avz -e "ssh -i /home/starsh/.ssh/id_ed25519 -o StrictHostKeyChecking=no" /tmp/fullbackup_*.sql starsh@192.168.122.20:/tmp/
      delegate_to: "pp-DBslave"
      become: false

    - name: Download completed
      debug:
        msg: Database have been downloaded successfully.
...
