---
- name: Configured MySQL servers pp-DMslave and restore databases
  hosts: pp-DBslave
  become: true
  vars_files:
    - inventory/group_vars/PPvars.yml
    - inventory/group_vars/DBvars.yml
    - inventory/group_vars/filebeat_vars.yml
  gather_facts: true

  handlers:
    - name: Restart mysql
      become: true
      ansible.builtin.systemd:
        name: mysql
        state: restarted

  tasks:
    - name: Ensure MySQL is installed
      ansible.builtin.apt:
        name:
          - mysql-server-8.0
          - mysql-client
          - python3-mysqldb
          - prometheus-node-exporter
        state: present
        update_cache: true

    - name: Ensure MySQL is runing and enabled
      ansible.builtin.systemd:
        name: mysql
        state: started
        enabled: true

    - name: Copy replica config file
      ansible.builtin.template:
        src: mysqld_replica.cnf.j2
        dest: /etc/mysql/mysql.conf.d/mysqld.cnf
      notify: Restart mysql

    - name: Copy backup mysql
      ansible.builtin.shell: |
        scp -o StrictHostKeyChecking=no -i /home/starsh/.ssh/id_ed25519 starsh@192.168.122.20:/tmp/fullbackup*.sql /tmp/fullbackup.sql
      delegate_to: pp-DBslave

    - name: Restarted mysql.service in pp-DBslave. Why? I don't know!
      ansible.builtin.systemd:
        name: mysql.service
        state: restarted
    
    - name: Stot replica
      community.mysql.mysql_replication:
        login_password: '{{ mysql_root_password }}'
        mode: stopreplica

    # - name: Is's restore databases
    #   ansible.builtin.shell: |
    #     mysql -u root -p123 < /tmp/fullbackup.sql
    #   become: true

    - name: Reset GTID on slave before restore
      ansible.builtin.shell: |
        mysql -u root -p123 -e "STOP SLAVE; RESET SLAVE ALL; RESET MASTER;"
      become: true

    - name: Restore database after GTID reset
      ansible.builtin.shell: |
        mysql -u root -p123 < /tmp/fullbackup.sql
      become: true

    - name: Configure replica
      community.mysql.mysql_replication:
        login_password: '{{ mysql_root_password }}'
        mode: changeprimary
        master_host: "{{ DBmaster }}"
        master_port: 3306
        master_user: repl
        master_password: '{{ mysql_replica_password }}'
        master_auto_position: true
#      ignore_errors: true

    - name: Start replica
      community.mysql.mysql_replication:
        login_password: '{{ mysql_root_password }}'
        mode: startreplica

# Установка и конфигурирование filebeat
    - name: Install deb package filebeat
      ansible.builtin.apt:
        deb: "{{ filebeat_deb }}"

    - name: Copy filebeat config
      ansible.builtin.template:
        src: filebeat.yml.j2
        dest: /etc/filebeat/filebeat.yml
        owner: root
        group: root
        mode: '0644'

    - name: Enable filebeat
      ansible.builtin.service:
        name: filebeat
        enabled: true
        state: 'started'
...
