---
- name: Configured MySQL servers pp-DBmaster pp-DMslave
  hosts: Databases
  become: true
  vars_files:
    - inventory/group_vars/PPvars.yml
    - inventory/group_vars/DBvars.yml
    - inventory/group_vars/filebeat_vars.yml
  gather_facts: true

  handlers:
    - name: Restart mysql
      become: true
      ansible.builtin.service:
        name: mysql
        state: restarted

  tasks:
    - name: Ensure MySQL is installed
      ansible.builtin.apt:
        name:
          - mysql-server-8.0
          - mysql-client
          - python3-mysqldb
          - prometheus-node-exporter
        state: present
        update_cache: true

    - name: Ensure MySQL is runing and enabled
      ansible.builtin.systemd:
        name: mysql
        state: started
        enabled: true

    - name: Copy main config file
      ansible.builtin.template:
        src: mysqld_main.cnf.j2
        dest: /etc/mysql/mysql.conf.d/mysqld.cnf
      notify: Restart mysql
      when: ansible_hostname == "pp-DBmaster"

    - name: Copy replica config file
      ansible.builtin.template:
        src: mysqld_replica.cnf.j2
        dest: /etc/mysql/mysql.conf.d/mysqld.cnf
      notify: Restart mysql
      when: ansible_hostname == "pp-DBslave"

    - name: Create main user
      community.mysql.mysql_user:
        login_password: '{{ mysql_root_password }}'
        name: repl
        host: '%'
        password: '{{ mysql_replica_password }}'
        priv: '*.*:REPLICATION SLAVE'
        state: present
      when: ansible_hostname == "pp-DBmaster"

    - name: Configure replica
      community.mysql.mysql_replication:
        login_password: '{{ mysql_root_password }}'
        mode: changeprimary
        master_host: "{{DBmaster}}"
        master_port: 3306
        master_user: repl
        master_password: '{{ mysql_replica_password }}'
        master_auto_position: true
      when: ansible_hostname == "pp-DBslave"

    - name: Start replica
      community.mysql.mysql_replication:
        login_password: '{{ mysql_root_password }}'
        mode: startreplica
      when: ansible_hostname == "pp-DBslave"

    - name: Create a new database with name 'wordpress'
      community.mysql.mysql_db:
        name: wordpress
        state: present
        login_unix_socket: /run/mysqld/mysqld.sock
      when: ansible_hostname == "pp-DBmaster"

    - name: Create user Wordpress and grant privileges on wordpress
      community.mysql.mysql_user:
        login_password: '{{ mysql_root_password }}'
        name: wordpress
        host: '%'
        password: wordpress
        priv: 'wordpress.*:ALL,GRANT'
      when: ansible_hostname == "pp-DBmaster"

    - name: Install deb package filebeat
      ansible.builtin.apt:
        deb: "{{ filebeat_deb }}"

    - name: Copy filebeat config
      ansible.builtin.template:
        src: filebeat.yml.j2
        dest: /etc/filebeat/filebeat.yml
        owner: root
        group: root
        mode: '0644'

    - name: Enable filebeat
      ansible.builtin.service:
        name: filebeat
        enabled: true
        state: 'started'

    # - name: Configure iptables rules from template
    #   template:
    #     src: iptables-rules.j2
    #     dest: /etc/iptables/rules.v4
    #     mode: 0644
    #   notify: Apply iptables rules
...
