---
- name: Configured monitoring, loging and alerting server
  hosts: pp-MLA
  become: true
  vars_files:
    - inventory/group_vars/PPvars.yml
    - inventory/group_vars/filebeat_vars.yml
  gather_facts: false

  vars:
    grafana_deb: "/packages/grafana-enterprise_12.3.0_19497075765_linux_amd64.deb"
    elasticsearch_deb: "/packages/elasticsearch-9.2.2-amd64.deb"
    logstash_deb: "/packages/logstash-9.2.2-amd64.deb"
    kibana_deb: "/packages/kibana-9.2.2-amd64.deb"

  handlers:
    - name: Restart prometheus
      ansible.builtin.systemd:
        name: prometheus
        state: restarted

    - name: Restart alertmanager
      ansible.builtin.systemd:
        name: prometheus-alertmanager
        state: restarted

    - name: Restart grafana
      ansible.builtin.systemd:
        name: grafana-server
        state: restarted

    - name: Restart elasticsearch
      ansible.builtin.systemd:
        name: elasticsearch
        state: restarted

    - name: Restart logstash
      ansible.builtin.systemd:
        name: logstash
        state: restarted

    - name: Restart kibana
      ansible.builtin.systemd:
        name: kibana
        state: restarted

  tasks:
    - name: Ensure prometheus is installed
      ansible.builtin.apt:
        name:
          - prometheus
          - prometheus-alertmanager
        state: present
        update_cache: true

    - name: Copy prometheus configs
      ansible.builtin.template:
        src: MLA/prometheus.yml.j2
        dest: /etc/prometheus/prometheus.yml
        owner: prometheus
        group: prometheus
        mode: '0644'
      notify: Restart prometheus

    - name: Install deb packages (grafana, ELK, filebeat)
      ansible.builtin.apt:
        deb: "{{ item }}"
      loop:
        - "{{ grafana_deb }}"
        - "{{ elasticsearch_deb }}"
        - "{{ logstash_deb }}"
        - "{{ kibana_deb }}"
        - "{{ filebeat_deb }}"

    - name: Enable grafana
      ansible.builtin.service:
        name: grafana-server
        enabled: true
        state: 'started'
    
    - name: Copy all config files grafana
      ansible.builtin.copy:
        src: files/grafana-config.tar.gz
        dest: /tmp/

    - name: Extract grafana directory /etc/grafana
      ansible.builtin.shell:
        tar -xzf /tmp/grafana-config.tar.gz --directory=/
      notify: Restart grafana

    - name: Copy config jvm.options
      ansible.builtin.template:
        src: MLA/jvm.options.j2
        dest: /etc/elasticsearch/jvm.options.d/jvm.options
        owner: root
        group: elasticsearch
        mode: '0644'

    - name: Copy elasticsearch config
      ansible.builtin.template:
        src: MLA/elasticsearch.yml.j2
        dest: /etc/elasticsearch/elasticsearch.yml
        owner: root
        group: elasticsearch
        mode: '0644'

    - name: Copy logstash config
      ansible.builtin.template:
        src: MLA/logstash.conf.j2
        dest: /etc/logstash/conf.d/logstash.conf
        owner: root
        group: root
        mode: '0644'

    - name: Copy kibana config
      ansible.builtin.template:
        src: MLA/kibana.yml.j2
        dest: /etc/kibana/kibana.yml
        owner: root
        group: root
        mode: '0644'

    - name: Copy filebeat config
      ansible.builtin.template:
        src: filebeat.yml.j2
        dest: /etc/filebeat/filebeat.yml
        owner: root
        group: root
        mode: '0644'

    - name: Enable service of ELK
      ansible.builtin.service:
        name: "{{ item }}"
        enabled: true
        state: 'started'
      loop:
        - kibana
        - logstash
        - filebeat
        - elasticsearch
...
