---
- name: Configured monitoring, loging and alerting server
  hosts: pp-MLA
  bacome: true
  vars_files: inventory/group_vars/PPvars.yml
  gather_facts: false

  vars:
    dirpack: "/packages"

  handlers:
    - name: Restart prometheus
      ansible.builtin.systemd:
        name: prometheus
        state: restarted

    - name: Restart alertmanager
      systemd:
        name: prometheus-alertmanager
        state: restarted

    - name: Restart grafana
      systemd:
        name: grafana-server
        state: restarted 

  tasks:
    - name: Ensure prometheus, ... is installed
      ansible.builtin.apt:
        name:
          - prometheus
          - prometheus-alertmanager
        state: present
        update_cache: true
  
    - name: Copy prometheus configs
      ansible.builtin.template:
        src: prometheus.yml.j2
        dest: /etc/prometheus/prometheus.yml
        owner: prometheus
        group: prometheus
        mode: '0600'
      notify: restart prometheus

    - name: Install grafana
      ansible.builtin.shell:





...